name: Build and Push Docker Images with MongoDB

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build et push du backend
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./mon_dossier
          file: ./mon_dossier/Dockerfile
          push: true
          tags: ndiaye2024/backend:latest

      # 4️⃣ Build et push du frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ndiaye2024/frontend:latest
