name: Build and Push Docker Images with MongoDB

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Login Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build and push backend
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./mon_dossier
          file: ./mon_dossier/Dockerfile
          push: true
          tags: ton_compte_dockerhub/backend:latest

      # 4️⃣ Build and push frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ton_compte_dockerhub/frontend:latest
